config/routes.rb
DressXMeUp::Application.routes.draw do
  get "items/index"
  get "items/show"

  root "pages#home"

  get "pages/home"
  get "pages/payment"
  get "pages/contact"

  resources :items, only: [:index,:show]

end

app/models/facebook.rb
class Facebook < ActiveRecord::Base
  serialize :value
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    # items = Facebook.find_by_name("Items")
    # if items.blank?
    #   value = @page.albums.map{ |a| {name: a.name, identifier: a.identifier, description: a.description, first_photo: a.photos.first.images[2].source} if a.name.match('Profile Pictures').blank? }.compact!
    #   items = Facebook.create(name: "Items", value: value)
    #   @items = items.value
    # else
    #   @items = items.value
    # end
    items = Facebook.find_by_name("Items")
    if items.updated_at < 30.minutes.ago
      Rails.logger.info "This 15m"
      app = FbGraph::Application.new(300450546746887, :secret => '71e6e5ab681e76090a2da7065905bb7a')
      @token = app.get_access_token
      @page = FbGraph::Page.fetch('dressxmeup', :access_token => @token)

      items = Facebook.find_by_name("Items")
      value = @page.albums({limit: 999}).map{ |a| {name: a.name, identifier: a.identifier, description: a.description, first_photo: a.photos.first.images[2].source} if a.name.match('Profile Pictures').blank? }.compact!
      items.value = value
      items.save
    end
    @items = items.value
  end

  def show
    @item = FbGraph::Album.fetch(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def payment
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/items/_index_item.html.erb
<div class="item col-md-3 col-sm-4 col-xs-6">
  <div class="thumbnail">
    <%= link_to item_path(item[:identifier]) do %>
      <div class="cover">
        <%= image_tag(item[:first_photo]) %>
      </div>
    <% end %>
    <div class="caption">
      <%= link_to "##{item[:name]}", item_path(item[:identifier]) %><br>
      <p class="text-right">
        <%= item[:description].split(",").first if item[:description].present? %>
      </p>
    </div>
  </div>
</div>

app/views/items/index.html.erb
<div class="row items">
  <% @items.each do |item| %>
    <%= render partial: "items/index_item", locals: {item: item} %>
  <% end %>
</div>

app/views/items/show.html.erb
<div class="row">  
  <div class="col-sm-12">
    <div class="row item">
      <div class="col-sm-3">
        <div class="item-detail">
          <h3><%= "##{@item.name}" %></h3>    
            <% if @item.description.present? %>
              <% @item.description.split(",").each do |d| %>
                <p><%= d %></p>
              <% end %>
            <% end %>   
        </div>
      </div>
      <div class="col-sm-6">
        <ul class="bxslider">
          <% @item.photos.each do |photo| %>
            <li><%= image_tag(photo.images.first.source, class:"img-responsive") %></li>
          <% end %>
        </ul>
      </div>
      <div class="col-sm-3">
        <div id="bx-pager">
          <div class="row">
            <% @item.photos.each_with_index do |photo,index| %>
              <div class="col-xs-4">
                <a data-slide-index=<%= index %> href="">
                  <%= image_tag(photo.images.first.source, class:"img-responsive") %>
                </a>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DressXMeUp</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <%= render "shared/header" %>
    </div>
    <div class="body">
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/pages/contact.html.erb
<div class ="row contact">
  <div class="col-sm-8 image">
    <%= image_tag("http://img1.etsystatic.com/000/0/5304180/il_fullxfull.291547823.jpg?ref=l2")%>
  </div>
  <div class="col-sm-4 content">
    <h5>Contact us</h5>
    <p>
      Line id – iiceezy
    </p>
    </p>
      Email – <a a href="mailto:dressxmeup@gmail.com">dressxmeup@gmail.com</a>
    <p>
    <p>
      Our customer service team will get back to you within 24 hours.
    </p>
  </div>
</div>

app/views/pages/home.html.erb
<div class="row">
  <%= render "shared/banner" %>
  <%= render "shared/new_arrival" %>
</div>

app/views/pages/payment.html.erb
<h1>Pages#payment</h1>
<p>Find me in app/views/pages/payment.html.erb</p>

app/views/shared/_banner.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
<!--   <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>
 -->
  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
      <%= image_tag("banner1.jpg")%>
    </div>
  </div>
  <!-- Controls -->
<!--   <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a> -->
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-4">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">DressXMeUp</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-4">
      <ul class="nav navbar-nav">
        <li><%= link_to "Items", items_path %></li>
        <li><%= link_to "Payment", pages_payment_path %></li>
        <li><%= link_to "Contact", pages_contact_path %></li>
      </ul>
    </div>
  </div>
</nav>